### PR TITLE
Load all attributes by default

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
load all map keyword for the given config

```
{ "menu": "organism", "config": { "default": ["Organism"], "all": ["Organism"], "ns": ["openmicroscopy.org/mapr/organism"], "label": "Organism", "wildcard": { "enabled": "True"} } }
```
ToDo:
 - tests

To test:

- click on Organism and **be patient** until the entire list is loaded :)

firefoxscreensnapz046

# SLOW, be patient ! :-)

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
To be honest this is so slow its not worth doing.  I would definitely have given up waiting and tried typing something but the time this loads.  Opening second window and trying a second time didn't see to speed it up.

**Comment by joshmoore** [comment]
@eleanorwilliams : I had the same experience, but @aleksandra-tarkowska pointed out that there's no caching on CI. We'll need to test on IDR.

**Comment by eleanorwilliams** [comment]
Ok, well it does do what its meant to do, so if its faster on IDR then it will be useful.

**Comment by joshmoore** [comment]
Looks good on test34. Merging for deployment on demo34.

**Pull request merged**
