### PR TITLE
fix return of default favicon if not found

### PR DESCRIPTION
**Pull request by will-moore**
Fixes return of default favicon if one is not loaded from domain.

cc @francesw 

To test, go to e.g. /mapr/favicon/?u=https%3A%2F%2Flod.humanatlas.io%2Fomap%2F18-lymph-node-cell-dive-ibex%2Fv1.0%2F and you should see a tiny globe icon shown on the page.

### CODE REVIEW

**Comment by francesw** [comment]
looks good on the pilot 
Screenshot 2024-10-03 at 16 04 50

**Comment by will-moore** [comment]
Test above was deployed on pilot idr0159:

```
sudo /opt/omero/web/venv3/bin/pip uninstall -y omero-mapr
sudo /opt/omero/web/venv3/bin/pip install git+https://github.com/ome/omero-mapr.git@refs/pull/86/head
sudo service omero-web restart
```
looking at images from idr0158...

**Comment by dominikl** [comment]
👍 Looks good, thanks Will!

**Comment by will-moore** [comment]
Merging as discussed...

**Pull request merged**
