### PR TITLE
fix url encoding and icons

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR fixes url encoding and loads favicons using internal webservice.

note package was renamed that means https://github.com/openmicroscopy/openmicroscopy/pull/4908 is needed

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
code freeze: deployed on 190 and 193 cc @manics

**Comment by joshmoore** [comment]
Shall we try to test this before the 0.3.0-rc1 tag?

**Comment by aleksandra-tarkowska** [comment]
yes, that is required for demo3, just realized small bug last night

**Comment by joshmoore** [comment]
But do we deploy a merge build before getting this into the tag? and if so, where?

**Comment by aleksandra-tarkowska** [comment]
https://github.com/openmicroscopy/openmicroscopy/pull/4900 is required

**Comment by joshmoore** [comment]
Merging for 0.1.6

**Pull request merged**
