### PR TITLE
load case insensitive data to the tree

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
This PR relaxe queries to load case insensitive data https://trello.com/c/M3q00BhI/55-mapr-case-insensitive-searching
google chromescreensnapz003

Test:

- **Case sensitive is only enabled in gene and compound tab** (configurable)
- Check:
  - mapr/gene/?value=cdc14
  - mapr/gene/?value=cdc14&case_sensitive=true
  - mapr/gene/?value=cdc14&case_sensitive=true&query=true
 **`case_sensitive` & `query` are not mutually exclusive**
- type `cdc14` in autocomplete and test `Match case`
- check if tests passes https://idr-ci.openmicroscopy.org:8443/job/MAPR-test/
- check help tooltip in `?` button

### CODE REVIEW

**Comment by manics** [comment]
Does this need to be an option or could it be simplified so it's always case-insensitive?

**Comment by aleksandra-tarkowska** [comment]
by default is case insensitive, the option is to filter with case sensitive

**Comment by manics** [comment]
I know, I was wondering whether it could always be case-insensitive to reduce the code complexity.

**Comment by aleksandra-tarkowska** [comment]
I don't know enough use cases to judge. Up to @eleanorwilliams, we briefly discussed that both options may be needed.

**Comment by eleanorwilliams** [comment]
@manics The casing of the gene symbols is to a certain extent different in different species e.g cdc14 in Drosophila, CDC14 in yeast so if you want to search for the gene in an narrower range of species you can do it using casing.

**Comment by eleanorwilliams** [comment]
I find it a little disconcerting that the autocomplete list shows the different casing options, but when i select one it gives me back all of them.  Maybe we need a check box that says 'return case-insensitive results' to make it more obvious that its going to do this.  

The good thing is that in the results it separates the results e.g. cdc14 and CDC14 are listed separately, so that even though the search is case insensitive you can still refine by the the more specific results.

**Comment by eleanorwilliams** [comment]
of course we also have the issue that the Gene Symbols are not always entered consistently - http://idr-ci.openmicroscopy.org:1880/web/mapr/gene/?value=YFR028C

**Comment by aleksandra-tarkowska** [comment]
@eleanorwilliams thanks for your suggestion, I will update the UI

**Comment by aleksandra-tarkowska** [comment]
I am done, ready for review

**Comment by aleksandra-tarkowska** [comment]
@eleanorwilliams I am done, ready for review. Please read description for reference of new changes.

**Comment by eleanorwilliams** [comment]
I like the check box.  I personally would not have it greyed out, I'd just have it obvious from the start.  And I'd change it to 'Match case'.  Otherwise all looks fine.

**Comment by aleksandra-tarkowska** [comment]
@eleanorwilliams thanks for feedback. updated

**Comment by aleksandra-tarkowska** [comment]
tests passing https://idr-ci.openmicroscopy.org:8443/job/MAPR-test/3/console

**Comment by aleksandra-tarkowska** [comment]
passed again https://idr-ci.openmicroscopy.org:8443/job/MAPR-test/5/console

**Comment by eleanorwilliams** [comment]
Works fine.  I noticed its only for genes and compounds (which are the two with issues) but any reason it couldn't be consistent across all mapr types?

Also the other thing that is slightly annoying is that if you check the box after you start typing the search goes away.  E.g. if you type cdc14 in to the gene box, see that there are lots of casing options and then click the checkbox to say you want it to be case sensitive, then the cdc14 that you typed is gone.  I don't know if there is an easy way round this.

**Comment by aleksandra-tarkowska** [comment]
as mentioned in the description availability of checkbox is configurable, it was done on purpose to allow testing and exploring both possibilities.

autocomplete is only triggered on typing, so match cases has to wipe a state of autocomplete otherwise it won't work. We can review that in a future.

**Comment by pwalczysko** [comment]
The tests https://idr-ci.openmicroscopy.org:8443/job/MAPR-test/ are not accessible to me. Site asks for credentials, and the most obvious username/pwd combinations fail for me.

**Comment by aleksandra-tarkowska** [comment]
thanks for testing, please provide final wording for both tooltips :)

**Comment by pwalczysko** [comment]
``Please select "Match case" or not as desired, then start typing to search for Gene symbol or Gene identifier. Select the desired item from the dropdown menu which appears after typing has started.``

The second tooltip on "Match case" is either fine or I would remove it completely, it does not really need a reformulation for me, or even be there (maybe @eleanorwilliams will have a better opinion)

**Comment by eleanorwilliams** [comment]
Text from @pwalczysko is good.  I think for the mapr categories where you can't select the match case box the tool tip shouldn't mention it.  In those cases just have 'Start typing to search for siRNA identifier or siRNA pool identifier. Select the desired item from the dropdown menu which appears after typing has started.' etc.

**Comment by eleanorwilliams** [comment]
Tools tips are good now.  @pwalczysko what do you think?

**Comment by pwalczysko** [comment]
Happy with the tooltips too, thank you.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore is yours now :)

**Comment by joshmoore** [comment]
Excellent! Demo tomorrow with @jrswedlow at the meeting and then let's get it in. Thanks, all.

**Comment by joshmoore** [comment]
From @jrswedlow:
> Really like the change— so yes, please move into production.  I can’t detect any issues with performance, but that might just be me.

**Comment by aleksandra-tarkowska** [comment]
thx everyone

**Comment by joshmoore** [comment]
Released as 0.1.11

**Pull request merged**
