### PR TITLE
Django 3 2

### PR DESCRIPTION
**Pull request by will-moore**
Updates mapr to work with Django 3.2 and https://github.com/ome/omero-web/pull/356

NB: URLs are case-sensitive. Could cause issues if any keys in `mapr_settings.CONFIG` are case sensitive?

### CODE REVIEW

**Comment by jburel** [comment]
``pytest-django`` might need to be updated too.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-plugins-push#1071](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1071/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-plugins-push/1071/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - requirements.txt

--conflicts

**Comment by jburel** [comment]
cf4168a9eb66ca9a186c1665c7bc643aaea0dc44 is required since other web apps are installed and configured via https://github.com/ome/omero-web-docker/blob/master/standalone/01-default-webapps.omero (docker image using in test-infra). In our case, mapr fails b/c of iviewer and parade.

**Comment by sbesson** [comment]
As an alternative to https://github.com/ome/omero-mapr/commit/cf4168a9eb66ca9a186c1665c7bc643aaea0dc44, we could either override `OMERO_WEB_IMAGE` and/or possible update https://github.com/ome/omero-test-infra/blob/337627dcb1862c85ccc1b1bdca446485f9bea193/.env#L11 so that the base OMERO.web image is used for testing by default. Within the scope of the integration tests of a particular app the base image should be sufficient.

On the other hand, does https://github.com/ome/omero-mapr/pull/70/commits/cf4168a9eb66ca9a186c1665c7bc643aaea0dc44 point to core configuration incompatibilities between our apps?

**Comment by jburel** [comment]
@sbesson I tried that and it leads to other issues.

**Comment by will-moore** [comment]
PR changes look good and https://merge-ci.openmicroscopy.org/web/mapr/gene/ is working.

**Comment by pwalczysko** [comment]
can confirm that mapr is fine, testedGene and the top Any KVp",  https://merge-ci.openmicroscopy.org/web/mapr/anyvalue/

**Comment by jburel** [comment]
Proposing to merge and tag as 0.5.0.
Any objections?

**Pull request merged**
