### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by eleanorwilliams**
Fixed first URL which was incorrect.  
Fixed layout of tables which were wrong due to | in table cell values. 
Added cellline and antibody to the list of mapr types. 

Apart from adding cellline and antibody to mapr types I have not altered content.  Is there anything else that needs updating?

### CODE REVIEW

**Comment by manics** [comment]
Looks a lot better!

Optional (can be left for the future):
- Add something like `TYPE=(gene|phenotype|cellline|sirna|antibody|compound|organism)` and just reference `TYPE` in the table instead of along string, so that the cell isn't so wide.
- Change `http` to `https`

**Comment by eleanorwilliams** [comment]
@manics I've changed <http> to <https> but I haven't done anything with the long <(gene|phenotype|cellline|sirna|antibody|compound|organism)> yet.  I'll add a card for that and do in the future.

**Comment by manics** [comment]
Good to merge

**Comment by joshmoore** [comment]
As an aside: to bring this closer to the OMERO mainline, we may need to un-IDR-ify some of the docs.

**Pull request merged**
