### PR TITLE
Reactivate test-infra with 5.6.0-m2

### PR DESCRIPTION
**Pull request by joshmoore**
Latest omero-web-docker image (5.6.0-m2-0) should allow imports.

### CODE REVIEW

**Comment by joshmoore** [comment]
Generally working again but is failing with:

```
>       raise NoReverseMatch(msg)
E       django.urls.exceptions.NoReverseMatch: Reverse for 'mapannotations_api_mapannotations' not found. 'mapannotations_api_mapannotations' is not a valid view function or pattern name.
/opt/omero/web/venv3/lib64/python3.6/site-packages/django/urls/resolvers.py:497: NoReverseMatch
```

cc: @will-moore

**Comment by will-moore** [comment]
I assume that ```omero-test-infra``` doesn't yet have https://github.com/ome/omero-web/pull/79 in it, so we could be missing failure to import ```urls.py```. I can try and reproduce locally...

**Comment by joshmoore** [comment]
No, that makes sense. I'll look into getting a release that includes 79 and then bump omero-test-infra.

**Comment by joshmoore** [comment]
@will-moore : still failing with 5.6.0-m3 which includes 5.6.0.dev6 which includes PR 76.

**Comment by will-moore** [comment]
Running ```.omero/docker app``` locally, if I try to ```from . import urls``` in ```omero_mapr.__init__``` I get:
```
+ python setup.py sdist
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    version = __import__('omero_mapr').get_version()
  File "/omero-mapr/omero_mapr/__init__.py", line 27, in <module>
    from . import urls
  File "/omero-mapr/omero_mapr/urls.py", line 23, in <module>
    from . import views
  File "/omero-mapr/omero_mapr/views.py", line 25, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Looking at the setup.py, the ```install_requires``` tries to read from ```requirements.py``` which *does* list ```requests``` as a dependency.

I don't see any of sign of it being installed in the travis or local console output, but then I also don't see the install of other omero-mapr dependencies, so don't know what's being installed?

**Comment by joshmoore** [comment]
See gh-57 for further discussion. In my testing, this sufficed to show the problem:

```
pip install .
python
>>> import omero_mapr.urls
```

**Comment by joshmoore** [comment]
Next error is:
```
(venv3) bash-4.2$ python -c "import omero_mapr.urls"
ERROR:omeroweb.webgateway.views:No numpy installed
```

I've added a commit after which the import test above fails, even though test-infra is still failing.

**Comment by joshmoore** [comment]
```
(venv3) bash-4.2$ pip freeze | grep omero-web
You are using pip version 9.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
omero-web==5.6.dev4
```

I imagine we're missing a bump elsewhere to have this working properly.

**Comment by manics** [comment]
OMERO.web isn't pinned in the ansible role (there's no released version so it will pip install the latest dev release), so rebuilding the docker image would also work. Though there are several updates to the role so probably good to bump it anyway.

**Comment by joshmoore** [comment]
It was pinned in https://github.com/ome/ansible-role-omero-web/pull/26/commits/283b8532706a7b880fc987a4cd575dfea99b94e2 though.

**Comment by will-moore** [comment]
```omeroweb.webgateway.views.py``` tries to import numpy to support masks but it is not essential. The Error is just a message in:

```
try:
    import numpy
    numpyInstalled = True
except ImportError:
    logger.error('No numpy installed')
    numpyInstalled = False
```

**Comment by joshmoore** [comment]
Force-pushed away the addition of numpy to requirements.txt in https://github.com/ome/omero-mapr/commit/328c51ef73918ae0b200f300bf4afa086e1a45eb, triggering another travis build with the new docker images (5.6.0-m3-1)

**Comment by joshmoore** [comment]
Unfortunately, still failing with 5.6.0.dev6. Passing back to @will-moore.

**Comment by will-moore** [comment]
This can be closed now that https://github.com/ome/omero-mapr/pull/58 is in?

**Comment by joshmoore** [comment]
Sure. If any of the other issues that were tackled here show up, we can always resurrect.

**Pull request closed without merging**
