### PR TITLE
Complete repo migration to the organization by updating references

### PR DESCRIPTION
**Pull request by sbesson**
/cc @aleksandra-tarkowska @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
:+1: thanks. Worth a bump to the version and a release once this is merged so we know that the process is working for someone other than @aleksandra-tarkowska ? (Eventually, this might should be an auto release on tag like pom-omero-client)

**Comment by sbesson** [comment]
Definitely thumbs up for a mini-relase: version bump, signed tag  and Pypi upload from my perspective. Want me to increase the version as part of this PR?

**Comment by joshmoore** [comment]
Sounds good to me.

**Comment by sbesson** [comment]
Pushed.

**Comment by joshmoore** [comment]
Nice. Attempting a release.

**Pull request merged**
